url: "https://www.rafaelostertag.photo"
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Photos"

include:
  - _DSC*.jpg
  - _DSC*.webp
  - _D85*.jpg
  - _D85*.webp
  - _NZ9*.jpg
  - _NZ9*.webp

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

defaults:
  - scope:
      path: license.md
    values:
      sitemap: false
  - scope:
      path: contact.html
    values:
      sitemap: false