url: "https://www.rafaelostertag.photo"
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Photos"

include:
  - _DSC*.jpg
  - _D85*.jpg
  - _NZ9*.jpg

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
